# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_dma/design_dma.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma || ORIG_REF_NAME==design_dma}]

# IP: bd/design_dma/ip/design_dma_Sample_Generator_0_0/design_dma_Sample_Generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_Sample_Generator_0_0 || ORIG_REF_NAME==design_dma_Sample_Generator_0_0}]

# IP: bd/design_dma/ip/design_dma_axi_dma_0_0/design_dma_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_axi_dma_0_0 || ORIG_REF_NAME==design_dma_axi_dma_0_0}]

# IP: bd/design_dma/ip/design_dma_processing_system7_0_0/design_dma_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_processing_system7_0_0 || ORIG_REF_NAME==design_dma_processing_system7_0_0}]

# IP: bd/design_dma/ip/design_dma_xlconstant_0_0/design_dma_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_xlconstant_0_0 || ORIG_REF_NAME==design_dma_xlconstant_0_0}]

# IP: bd/design_dma/ip/design_dma_xlconstant_1_0/design_dma_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_xlconstant_1_0 || ORIG_REF_NAME==design_dma_xlconstant_1_0}]

# IP: bd/design_dma/ip/design_dma_axi_gpio_0_0/design_dma_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_axi_gpio_0_0 || ORIG_REF_NAME==design_dma_axi_gpio_0_0}]

# IP: bd/design_dma/ip/design_dma_axi_gpio_1_0/design_dma_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_axi_gpio_1_0 || ORIG_REF_NAME==design_dma_axi_gpio_1_0}]

# IP: bd/design_dma/ip/design_dma_ps7_0_axi_periph_0/design_dma_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_dma_ps7_0_axi_periph_0}]

# IP: bd/design_dma/ip/design_dma_rst_ps7_0_100M_0/design_dma_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_dma_rst_ps7_0_100M_0}]

# IP: bd/design_dma/ip/design_dma_xbar_0/design_dma_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_xbar_0 || ORIG_REF_NAME==design_dma_xbar_0}]

# IP: bd/design_dma/ip/design_dma_axi_mem_intercon_0/design_dma_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_axi_mem_intercon_0 || ORIG_REF_NAME==design_dma_axi_mem_intercon_0}]

# IP: bd/design_dma/ip/design_dma_auto_pc_0/design_dma_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_auto_pc_0 || ORIG_REF_NAME==design_dma_auto_pc_0}]

# IP: bd/design_dma/ip/design_dma_auto_pc_1/design_dma_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_auto_pc_1 || ORIG_REF_NAME==design_dma_auto_pc_1}]

# IP: bd/design_dma/ip/design_dma_auto_us_0/design_dma_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_dma_auto_us_0 || ORIG_REF_NAME==design_dma_auto_us_0}]

# XDC: bd/design_dma/ip/design_dma_axi_dma_0_0/design_dma_axi_dma_0_0_ooc.xdc

# XDC: bd/design_dma/ip/design_dma_axi_dma_0_0/design_dma_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_dma_axi_dma_0_0 || ORIG_REF_NAME==design_dma_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_dma/ip/design_dma_axi_dma_0_0/design_dma_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_dma_axi_dma_0_0 || ORIG_REF_NAME==design_dma_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_dma/ip/design_dma_processing_system7_0_0/design_dma_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_dma_processing_system7_0_0 || ORIG_REF_NAME==design_dma_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/design_dma/ip/design_dma_axi_gpio_0_0/design_dma_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_dma_axi_gpio_0_0 || ORIG_REF_NAME==design_dma_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_dma/ip/design_dma_axi_gpio_0_0/design_dma_axi_gpio_0_0_ooc.xdc

# XDC: bd/design_dma/ip/design_dma_axi_gpio_0_0/design_dma_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_dma_axi_gpio_0_0 || ORIG_REF_NAME==design_dma_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_dma/ip/design_dma_axi_gpio_1_0/design_dma_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_dma_axi_gpio_1_0 || ORIG_REF_NAME==design_dma_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_dma/ip/design_dma_axi_gpio_1_0/design_dma_axi_gpio_1_0_ooc.xdc

# XDC: bd/design_dma/ip/design_dma_axi_gpio_1_0/design_dma_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_dma_axi_gpio_1_0 || ORIG_REF_NAME==design_dma_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_dma/ip/design_dma_rst_ps7_0_100M_0/design_dma_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_dma_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_dma_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/design_dma/ip/design_dma_rst_ps7_0_100M_0/design_dma_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_dma_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_dma_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/design_dma/ip/design_dma_rst_ps7_0_100M_0/design_dma_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/design_dma/ip/design_dma_xbar_0/design_dma_xbar_0_ooc.xdc

# XDC: bd/design_dma/ip/design_dma_auto_pc_0/design_dma_auto_pc_0_ooc.xdc

# XDC: bd/design_dma/ip/design_dma_auto_pc_1/design_dma_auto_pc_1_ooc.xdc

# XDC: bd/design_dma/ip/design_dma_auto_us_0/design_dma_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_dma_auto_us_0 || ORIG_REF_NAME==design_dma_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/design_dma/ip/design_dma_auto_us_0/design_dma_auto_us_0_ooc.xdc

# XDC: bd/design_dma/design_dma_ooc.xdc
